### ISSUE TITLE
Error inserting snippet

### ISSUE THREAD

**Issue by patrick-mota** [gethoard/hoard-open#1]
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dockerapp`.`snippets`, CONSTRAINT `snippets_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)) (SQL: insert into `snippets` (`name`, `extension`, `description`, `updated_at`, `created_at`) values (CodeSniffer, conf, test, 2016-01-07 15:36:18, 2016-01-07 15:36:18))

Seems we don't insert the users_id which is mandatory as foreign key in snippet entity.

**Comment by edcrampin** [comment]
Hi @patrick-mota,

Thanks for the error report! This should now be fixed in commit ee70e7a.

Ed.

**Comment by patrick-mota** [comment]
Hi @edcrampin Thank you.
I've successfuly build a container with your app, but since I didn't knew much of Laravel, I had to try some parameters which aren't necessary anymore in my docker-compose.
If you want I can send you a pull request, when I finish to clean up, to integrate a docker-compose.yml in your project so people can build it fast with Docker (just with git clone, docker-compose build, docker-compose up)
