### ISSUE TITLE
Has this project been abandoned? 

### ISSUE THREAD

**Issue by vpakg** [gethoard/hoard-open#3]
Has this project been abandoned? The site is down there has been no updates for a while. 

Thanks.

**Comment by xadz** [comment]
Hi Victor! Thank you for your interest. I hit a bit of a skills block with the development here but it's definitely still something I plan to pursue as I continue to learn. 😄

**Comment by vpakg** [comment]
Great to hear. I hope it goes through.
Best of luck!
